### PR TITLE
[HOTFIX#198] Fixed UX problem by displaying "No proposals" when no proposals are available in ProposalListWidget 

### LINKED ISSUE #198: Le tabelle delle proposte non forniscono alcun feedback all'utente quando non c'è alcuna proposta disponibile compromettendo l'UX per l'utente
Come da titolo

### PR DESCRIPTION
**Pull request by alessioarcara**
This PR addresses the UX issue described in issue #198 by adding a text placeholder when no data is present and refactoring the UserListWidget and ProposalListWidget to extend the BaseListWidget.
The BaseListWidget class was also added to eliminate duplicated code and provide common behavior such as handling the text for no data and adding a header to the table.

### CODE REVIEW

**Review by dstops — CHANGES_REQUESTED** [review]
There is a little bug. text "no proposals" is shown above the actual proposal

**Comment by alessioarcara** [comment]
> There is a little bug. text "no proposals" is shown above the actual proposal

settled it!

**Review by dstops — APPROVED** [review]
I confirm that the bug has been fixed. Well done!!!

**Review by Matte0Sacc0 — APPROVED** [review]
Good Job, nice to have a generic object for all listable ones!!!

**Pull request merged**
